[package]
name = "json-with-comments"
authors = ["hayas1 <h4ystack@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.196"
thiserror = "1.0.57"

[dev-dependencies]
serde = { version = "1.0.196", features = ["derive"] }
