name: Master

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Release test
      run: cargo test --release

    - name: Run doc
      run: cargo doc --no-deps

    - name: Coverage
      run: >
        cargo install cargo-tarpaulin &&
          cargo tarpaulin --output-dir target/doc --manifest-path Cargo.toml --out Html

    - name: Remove 600 permission files
      run: find target/doc -perm 600 | xargs rm -rf

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release-draft:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/versions
      id: version-tag
    - name: Push tag
      if: steps.version-tag.outputs.should-release == 'true'
      run: |
        git tag ${{ steps.version-tag.outputs.expected-git-tag }}
        git push origin ${{ steps.version-tag.outputs.expected-git-tag }}
    - name: Release draft
      uses: actions/create-release@v1
      if: steps.version-tag.outputs.should-release == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version-tag.outputs.expected-git-tag }}
        release_name: ${{ steps.version-tag.outputs.expected-git-tag }}
        draft: true
