name: "Test workflow"

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup

    - run: cargo test --verbose
    - run: cargo fmt --check
    # - run: cargo clippy

    - run: cargo install cargo-readme && cargo readme > README.md
    - run: git add -N . && git diff --exit-code -- README.md
